describe('form test', () => {
    beforeEach(() => {
        cy.visit('localhost:3000')
    })
    it('sanity checks', () => {
        expect(1+2).to.equal(3)
    })
    const nameIntup = () => cy.get('input[name="name"]')
    const emailInput = () => cy.get('input[name="email"]')
    const passwdInput = () => cy.get('input[name="password"]')
    const checkBox = () => cy.get('input[type="checkbox"]')
    const sumbitButton = () => cy.get('#subbutt')
    it('can get name input and type in it', () => {
        nameIntup()
        .should('have.value', '')
        .type('Ryan')
        .should('have.value','Ryan')
    })
    it('can get email and type in it', () => {
        emailInput()
        .should('have.value', '')
        .type('ry@ryan.com')
        .should('have.value', 'ry@ryan.com')
    })
    it('can get password input and type in it', () => {
        passwdInput()
        .should('have.value', '')
        .type('Passw4rd')
        .should('have.value', 'Passw4rd')
    })
    it('checkbox can be checked', () => {
        checkBox()
        .click()
    })
    it('user can submit a form', () => {
        sumbitButton().should('exist')
        sumbitButton().should('be.disabled')
        nameIntup().type('Bilbo')
        emailInput().type('bilbo@theshire.com')
        passwdInput().type('BilbosPAssW4rd')
        checkBox().click()
        sumbitButton().should('be.enabled')
    })
    it('form has been submitted', () => {
        sumbitButton().should('exist')
        sumbitButton().should('be.disabled')
        nameIntup().type('Bilbo')
        emailInput().type('bilbo@theshire.com')
        passwdInput().type('BilbosPAssW4rd')
        checkBox().click()
        sumbitButton().should('be.enabled')
        sumbitButton().click()
        sumbitButton().should('be.disabled')
    })
    it('form is valid after validation checks all input fields have a truthy value', () => {
        sumbitButton().should('be.disabled')
        nameIntup().type('A Name')
        emailInput().type('email@emails.org')
        passwdInput().type('Passw4rd')
        checkBox().click()
        sumbitButton().should('be.enabled')
    })

})