
describe('Form tests', () => {
    beforeEach( () => {
        cy.visit('http://localhost:3000')
    })
    it('sanity check', () => {
        expect(1+4).to.equal(10-5)
    })
    const nameInput = () => cy.get('input[name="name"]')
    const emailInput = () => cy.get('input[name="email"]')
    const passwdInput = () =>  cy.get('input[name="password"]')
    const checkBox = () => cy.get('input[type="checkbox"]')
    const submitButton = () => cy.get('#subbutt')
    const errs = () => cy.get('#error')
    
    it('Can get input fields for name,email,password and can type inside', () => {
        nameInput()
        .should('have.value', '')
        .type('MaName')
        .should('have.value', 'MaName')
        emailInput()
        .should('have.value', '')
        .type('your@email.org')
        .should('have.value', 'your@email.org')
        passwdInput()
        .should('have.value', '')
        .type('Passw4rd')
        .should('have.value', 'Passw4rd')
    })
    it('a user can click to check and uncheck checkox field', () => {
        checkBox()
        .should('have.value', 'false')
        .click()
        .should('have.value', 'true')
        .click()
        .should('have.value', 'false')
    })
    it('User can submit the form data', () => {
        submitButton()
        .should('be.disabled')
        nameInput().type('Bilbo')
        emailInput().type('bilbo@theshire.org')
        passwdInput().type('Passw4rd')
        checkBox().click()
        submitButton()
        .should('not.be.disabled')
        .click()
        submitButton()
        .should('be.disabled')
    })
    it('Checking form validation. if an input is left empty it should display required', () => {
        errs()
        .should('have.value', '')
        nameInput()
        .type('abcdefg')
        .clear()
        errs()
        .should('have.html', 'a name is required')
        emailInput()
        .type('abc@123.net')
        .clear()
        .next().should('have.html', 'an email is required')
        passwdInput()
        .type('aPassw4rd')
        .clear()
        .next().should('have.html', 'need to fill in password')
        checkBox()
        .click()
        .click()
        .next().should('have.html', 'agree to terms')
    })
})